spring.application.name=CriminalRecord

# Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/police_records_db
spring.datasource.username = root
spring.datasource.password = NEW_PASSWORD

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=boobalansmsb@gmail.com
spring.mail.password=vplqmkecbsmhwkzq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Storage Paths
app.storage.encrypted-files=./police-storage/encrypted/
app.storage.private-keys=./police-storage/private-keys/

# RSA Key Size
app.rsa.key-size=2048

# JWT Secret
app.jwt.secret=policecriminalrecordssecretkey2024strongkey
app.jwt.expiration=86400000

# Face storage
app.storage.face-images=./police-storage/face-images/
